'''
Este codigo realiza la función de traducir los campos que obtenermos a la hora de sacar la información del archivo CSV
en los campos que contiene el documento Word
'''

campos_programa = {"Fecha_de_envío": "a1", "Nombre": "a2", "Apellidos": "a3", "DNI__NIE__PASAPORTE": "a4", "Sexo": "a5",
                   "Fecha_de_nacimiento": "a6", "Edad": "a7", "Teléfono": "a8", "correo": "a9", "Eres_de_España": "a10",
                   "Eres_de_Granada": "a11", "Codigo_Postal": "a12", "Nivel_de_español": "a13",
                   "Nivel_de_inglés": "a14",
                   "Vives_con_tu_familia": "a15", "Donde_vives_durante_el_curso": "a16", "Trabajas_actualmente": "a17",
                   "Que_tipo_de_contrato": "a18", "Titulación": "a19", "Año_de_inicio_de_la_titulación": "a20",
                   "Tipo_de_matrícula": "a21", "De_cuántos_créditos_estás_matriculado_este_curso": "a22",
                   "De_los_créditos_que_tiene_la_titulación_cuántos_has_superado": "a23",
                   "De_los_créditos_que_tiene_la_titulación_cuántos_has_cursado_y_NO_has_superado": "a24",
                   "De_las_asignaturas_NO_superadas_Cuántas_son_de_primera_convocatoria": "a25",
                   "De_las_asignaturas_NO_superadas_Cuántas_son_de_segunda_convocatoria": "a26",
                   "De_las_asignaturas_NO_superadas_Cuántas_son_de_tercera_convocatoria": "a27",
                   "Estas_cursando_la_titulación_que_querías": "a28", "Como_accediste_a_la_titulación": "a29",
                   "Tiene_alguna_otra_titulación": "a30", "Has_cambiado_alguna_vez_de_titulación": "a31",
                   "Has_dejado_alguna_vez_los_estudios": "a32",
                   "Eres_estudiante_con_Necesidades_Especificas_de_Apoyo_Educativo": "a33",
                   "Cómo_has_conocido_este_servicio": "a34", "Explica_en_qué_consiste_tu_demanda": "a35",
                   "Qué_objetivos_te_propones_conseguir_con_este_asesoramiento": "a36", "Emocionales": "a37",
                   "conducta": "a38", "hiper": "a39", "problemas": "a40", "prosocial": "a41", "flexi": "a42",
                   "plani": "a43", "control": "a44", "organi": "a45", "monito": "a46", "inhibi": "a47", "inici": "a48",
                   "memoria": "a49",
                   "Procuro_ser_agradable_con_los_demás_Tengo_en_cuenta_los_sentimientos_de_las_otras_personas": "a50",
                   "Soy_inquietoa_hiperactivoa_me_resulta_difícil_permanecer_sentadoa_durante_mucho_tiempo": "a51",
                   "Suelo_tener_muchos_dolores_de_cabeza_estómago_o_náuseas": "a52",
                   "Normalmente_comparto_mis_cosas_con_otras_personas_por_ejemplo_comida_y_bebida": "a53",
                   "Cuando_me_enfado_me_enfado_mucho_y_pierdo_el_control": "a54",
                   "Prefiero_estar_soloa_a_estar_con_gente": "a55",
                   "En_general_estoy_dispuestoa_a_hacer_lo_que_otras_personas_quieren": "a56",
                   "A_menudo_estoy_preocupadoa": "a57", "Ayudo_si_alguien_está_enfermo_disgustado_o_herido": "a58",
                   "Estoy_todo_el_tiempo_moviéndome_me_muevo_demasiado": "a59",
                   "Tengo_una_buena_amigoa_por_lo_menos": "a60",
                   "Peleo_con_frecuencia_puedo_conseguir_que_otras_personas_hagan_lo_que_yo_quiero": "a62",
                   "Me_siento_a_menudo_triste_desanimadoa_o_con_ganas_de_llorar": "a63",
                   "Por_lo_general_caigo_bien_a_la_gente": "a64",
                   "Me_distraigo_con_facilidad_me_cuesta_concentrarme": "a65",
                   "Me_pongo_nerviosoa_con_las_situaciones_nuevas_fácilmente_pierdo_la_confianza_en_mí_mismoa": "a66",
                   "Soy_amable_con_los_niños": "a67", "A_menudo_me_acusan_de_mentir_o_de_hacer_trampas": "a68",
                   "Otras_personas_se_meten_conmigo_o_se_burlan_de_mí": "a69",
                   "A_menudo_me_ofrezco_para_ayudar_a_los_demás_familiares_amigosas_compañerosas": "a70",
                   "Pienso_las_cosas_antes_de_hacerlas": "a71",
                   "Cojo_cosas_que_no_son_mías_de_casa_del_trabajo_o_de_otros_sitios": "a72",
                   "Me_llevo_mejor_con_personas_que_son_mayores_que_yo_que_con_gente_de_mi_edad": "a73",
                   "Tengo_muchos_miedos_me_asusto_fácilmente": "a74",
                   "Termino_lo_que_empiezo_tengo_buena_concentración": "a75",
                   "_Tengo_dificultades_para_recoger_y_dejar_ordenadas_mis_cosas_cuando_se_me_pide_que_lo_haga": "a76",
                   "_Necesito_tener_alguien_cerca_para_que_me_ayude_a_terminar_una_tarea_cuando_es_muy_larga": "a77",
                   "_Actúo_sin_pensar_haciendo_lo_primero_que_pasa_por_mi_mente": "a78",
                   "_Tengo_dificultad_para_admitir_mis_errores": "a79",
                   "_Me_cuesta_atender_a_las_instrucciones_que_se_me_indican": "a80",
                   "_Cometo_errores_por_descuido": "a81", "_Me_enfado_por_cosas_insignificantes": "a82",
                   "_Tengo_dificultades_para_tomar_decisiones_en_forma_independiente": "a83",
                   "_Dejo_tiradas_mis_cosas_por_todas_partes": "a84",
                   "_Tengo_dificultades_para_encontrar_rápidamente_mis_materiales_al_buscarlos_en_mi_cuarto"
                   "_o_escritorio": "a85", "_Me_cuesta_realizar_las_tareas_sin_ayuda_de_los_demás": "a86",
                   "_Soy_lentoa_en_la_realización_de_mis_tareas_académicas_y_del_hogar": "a87",
                   "_Me_cuesta_concentrarme": "a88",
                   "_Tengo_dificultades_para_esperar_tranquilamente_a_que_llegue_mi_turno": "a89",
                   "_Estoy_moviéndome_no_puedo_estar_quietoa": "a90",
                   "_Hago_mal_mis_tareas_porque_no_sigo_las_instrucciones_que_se_me_dan": "a91",
                   "_Me_cuesta_hacer_buenas_propuestas_para_resolver_problemas": "a92",
                   "_Tengo_dificultad_para_escuchar_atentamente": "a93",
                   "_Cuando_me_enfado_tengo_dificultad_para_calmarme_con_facilidad": "a94",
                   "_Parece_que_tengo_ganas_de_hacer_cosas_pero_enseguida_me_olvido_de_ellas": "a95",
                   "_Interfiero_o_interrumpo_las_actividades_de_los_demás": "a96",
                   "_Me_resulta_difícil_pensar_o_planificar_las_cosas_con_antelación": "a97",
                   "_Me_cuesta_cambiar_de_una_tarea_a_otra": "a98",
                   "_Me_cuesta_mantener_la_atención_en_una_actividad": "a99",
                   "_Necesito_de_alguien_que_me_supervise_para_realizar_mis_tareas_académicas": "a100",
                   "_Tengo_dificultades_para_cuidar_mis_pertenencias": "a101",
                   "_Me_perturban_los_cambios_de_planes": "a102",
                   "_Hago_mis_tareas_académicas_de_forma_apresurada": "a103",
                   "_Tengo_dificultad_para_hacer_todas_mis_tareas_académicas_sin_detenerme": "a104",
                   "_Me_cuesta_trabajo_encontrar_mis_cosas_cuando_las_necesito": "a105",
                   "_Me_resulta_difícil_comportarme_adecuadamente_en_las_reuniones_sociales": "a106",
                   "_Me_resulta_difícil_dejar_de_hacer_algo_cuando_se_me_pide_que_no_lo_haga_más": "a107",
                   "_Interrumpo_a_los_demás_cuando_están_hablando": "a108",
                   "_Me_cuesta_anticipar_las_consecuencias_de_mis_actos": "a109",
                   "__Necesito_de_la_ayuda_de_otra_persona_para_terminar_las_tareas": "a110",
                   "_Necesito_que_me_animen_constantemente_para_comenzar_a_hacer_mis_tareas_académicas_y_del"
                   "_hogar": "a111", "_Protesto_cuando_no_se_me_deja_hacer_lo_que_quiero": "a112",
                   "_Me_resulta_difícil_concentrarme_en_el_desarrollo_de_todo_tipo_de_juegos_p"
                   "_ej_Juegos_de_mesa": "a113",
                   "_Olvido_revisar_las_tareas_después_de_terminarlas": "a114",
                   "_Tengo_dificultades_para_tomar_decisiones_incluso_ante_las_cosas_más_sencillas": "a115",
                   "_Me_resulta_difícil_centrarme_en_algo": "a116",
                   "_Puedo_llegar_a_decir_cosas_inadecuadas_a_otras_personas": "a117",
                   "_Tengo_dificultades_para_realizar_apropiadamente_actividades_o_tareas_que_tienen_más_"
                   "de_un_paso": "a118", "_Me_es_difícil_regresar_a_una_tarea_después_de_tomar_un_descanso": "a119",
                   "_Olvido_revisar_el_material_antes_de_ir_a_la_Universidad": "a120",
                   "_Me_levanto_de_la_silla_o_abandono_mi_lugar_cuando_no_debo_hacerlo": "a121",
                   "_Necesito_que_se_me_diga_que_comience_una_tarea_aunque_tenga_ganas_de_hacerla": "a122",
                   "_Me_altero_o_pierdo_el_control_cuando_se_extravía_algo": "a123",
                   "_Tengo_dificultades_para_adaptarme_a_los_cambios_de_mis_rutinas_a_nuevos_profesores_o_a_cambios_"
                   "en_los_planes_familiares": "a124", "_Me_decepciono_fácilmente": "a125",
                   "_Parece_que_voy_dejando_todo_desordenado_por_donde_paso": "a126",
                   "_Me_distraigo_fácilmente": "a127",
                   "_Debo_esforzarme_incluso_en_las_asignaturas_que_me_gustan": "a128",
                   "_Olvido_llevar_a_casa_el_material_para_completar_las_tareas_académicas": "a129",
                   "_Me_molesto_fácilmente": "a130",
                   "_Me_cuesta_estar_dispuestoa_a_iniciar_las_tareas_con_sólo_proponérmelas": "a131",
                   "_Tengo_problemas_para_concentrarme_en_la_realización_de_tareas_académicas_y_del_hogar": "a132",
                   "_Me_quedo_en_los_detalles_de_la_tarea_y_pierdo_el_objetivo_principal": "a133",
                   "_Me_resisto_a_resolver_de_forma_diferente_tareas_académicas_juegos_con_amigos_tareas_del"
                   "_hogar_etc": "a134", "_Mi_desorden_tiene_que_ser_recogido_por_otros": "a135",
                   "_Tengo_dificultad_para_terminar_mis_trabajos_a_tiempo": "a136",
                   "_Me_cuesta_tener_buenos_hábitos_de_estudio": "a137",
                   "_Tengo_cambios_de_ánimo_de_forma_sorpresiva_triste_alegre_miedoso_sorprendido": "a138",
                   "_Me_cuesta_tener_iniciativa_para_comenzar_actividades_juegos_o_tareas_académicas": "a139",
                   "_Me_cuesta_tener_muchas_ideas": "a140", "_Me_olvido_de_las_cosas": "a141",
                   "_Pierdo_el_control_de_mis_emociones": "a142", "Me_siento_tensoa_o_nerviosoa": "a143",
                   "Todavía_disfruto_con_lo_que_antes_me_gustaba": "a144",
                   "Tengo_una_sensación_de_miedo_como_si_algo_horrible_me_fuera_a_suceder": "a145",
                   "Puedo_reírme_y_ver_el_lado_divertido_de_las_cosas": "a146",
                   "Tengo_mi_mente_llena_de_preocupaciones": "a147", "Me_siento_alegre": "a148",
                   "Puedo_estar_sentadoa_confortablemente_y_sentirme_relajadoa": "a149",
                   "Me_siento_como_si_cada_día_estuviera_más_lentoa": "a150",
                   "Tengo_una_sensación_extraña_como_si_tuviera_mariposas_en_el_estómago": "a151",
                   "He_perdido_interés_en_mi_aspecto_personal": "a152",
                   "Me_siento_inquietoa_como_si_no_pudiera_parar_de_moverme": "a153",
                   "Me_siento_optimista_respecto_al_futuro": "a154",
                   "Me_asaltan_sentimientos_repentinos_de_pánico": "a155",
                   "Me_divierto_con_un_buen_libro_la_radio_o_un_programa_de_televisión": "a188",
                   "_Técnicas_de_estudio": "a156", "_Rendimiento_académico": "a157",
                   "_Ansiedad_ante_los_exámenes": "a158",
                   "_Relaciones_con_los_demás_amigos_familia_pareja_profesores": "a159",
                   "_MiedoAnsiedad_a_hablar_en_público": "a160",
                   "_Habilidades_sociales_pedir_ayuda_hacerrecibir_crítica_decir_que_no": "a161",
                   "_Gestión_del_estrés": "a162",
                   "_Procrastinar_dejar_para_mañana_y_abandono_de_actividades_relevantes": "a163",
                   "_Tomar_decisiones": "a164", "_Alimentación": "a165", "_Sueño": "a166", "_Ejercicio_físico": "a167",
                   "_Ociotiempo_libre": "a168", "_Relaciones_Sexuales": "a169",
                   "_Consumo_de_sustancias_alcohol_tabaco_cannabis": "a170", "_Juegos_de_azarapuestas": "a171",
                   "_Hacerme_dañoautolesionarme": "a172", "_Adicciones_redes_sociales_videojuegos": "a173",
                   "Has_recibido_atención_psicológica_anteriormente_": "a174", "Dónde_la_ha_recibido": "a175",
                   "Cuándo": "a176", "Durante_cuánto_tiempo_": "a177", "Por_qué_la_recibiste": "a178",
                   "Qué_resultados_obtuviste": "a179", "Tiempo_total": "a180",
                   "Temporización_del_grupo_Consentimiento": "a181", "Temporización_del_grupo_Datos_Personales": "a182",
                   "Temporización_del_grupo_Datos_Académicos": "a183", "Temporización_del_grupo_Matrices": "a184",
                   "Temporización_del_grupo_Atención_Psicológica_Previa": "a185", "Depresion": "a186",
                   "Ansiedad": "a187", "Si_hay_algo_que_quiera_comentar_puede_hacerlo_en_este_apartado": "a189"}


def traducir(campo):
    nuevo_diccionario = {}
    for i in campo:
        try:
            nuevo_diccionario[campos_programa[i]] = campo[i]
        except KeyError:
            pass

    return nuevo_diccionario
